"""add votes table

Revision ID: 68fc711ccded
Revises: c1406f4a41b9
Create Date: 2023-06-18 17:50:12.498664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fc711ccded'
down_revision = 'c1406f4a41b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
  
    op.create_table('votes',
    sa.Column('ID_user', sa.Integer(), nullable=False),
    sa.Column('ID_post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_post'], ['Post_user.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_user'], ['Users.ID_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_user', 'ID_post')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
