"""addcolumn to user table

Revision ID: a8d08f29ff8f
Revises: 68fc711ccded
Create Date: 2023-06-18 18:15:54.984466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d08f29ff8f'
down_revision = '68fc711ccded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users',
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    )
 
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users',"phone_number")
    # ### end Alembic commands ###
